"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export function MemberJoinForm({slug,signedIn}:{slug:string;signedIn:boolean}){
  const router=useRouter();const [mode,setMode]=useState<"signup"|"signin">("signup");const [loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  async function attach(name:string,code:string){const response=await fetch("/api/member-join",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,code,name})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??"Anslutningen misslyckades.");router.replace("/dashboard");router.refresh()}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");setNotice("");const form=new FormData(event.currentTarget);const name=String(form.get("name")??""),code=String(form.get("code")??""),email=String(form.get("email")??"").trim().toLowerCase(),password=String(form.get("password")??"");try{
    if(signedIn){await attach(name,code);return;}
    const supabase=createClient();
    if(mode==="signin"){const {error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError)throw new Error(authError.message);await attach(name,code);return;}
    const {data,error:authError}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:window.location.href}});if(authError)throw new Error(authError.message);if(!data.session){setNotice("Kontrollera din e-post och bekräfta kontot. Öppna sedan medlemslänken igen och välj Logga in.");return;}await attach(name,code);
  }catch(caught){const message=caught instanceof Error?caught.message:"";if(message.toLowerCase().includes("invalid login"))setError("Fel e-postadress eller lösenord.");else if(message.toLowerCase().includes("already registered"))setError("Det finns redan ett konto. Välj Logga in.");else setError(message||"Anslutningen misslyckades.");}finally{setLoading(false)}}
  return <div className="mt-7">{!signedIn?<div className="grid grid-cols-2 rounded-lg bg-zinc-100 p-1"><button type="button" onClick={()=>setMode("signup")} className={`min-h-10 rounded-md text-sm font-semibold ${mode==="signup"?"bg-white shadow-sm":"text-zinc-600"}`}>Skapa konto</button><button type="button" onClick={()=>setMode("signin")} className={`min-h-10 rounded-md text-sm font-semibold ${mode==="signin"?"bg-white shadow-sm":"text-zinc-600"}`}>Logga in</button></div>:<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">Du är inloggad. Ange namn och skolkod för att ansluta.</p>}
    <form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-medium">Namn<input name="name" required minLength={2} maxLength={120} autoComplete="name" className="mt-1 block min-h-11 w-full rounded-lg border border-zinc-300 px-3"/></label><label className="block text-sm font-medium">Skolkod<input name="code" required autoCapitalize="characters" autoComplete="off" className="mt-1 block min-h-11 w-full rounded-lg border border-zinc-300 px-3 font-mono uppercase tracking-wider"/></label>{!signedIn?<><label className="block text-sm font-medium">E-postadress<input name="email" type="email" required autoComplete="email" className="mt-1 block min-h-11 w-full rounded-lg border border-zinc-300 px-3"/></label><label className="block text-sm font-medium">Lösenord<input name="password" type="password" required minLength={8} autoComplete={mode==="signup"?"new-password":"current-password"} className="mt-1 block min-h-11 w-full rounded-lg border border-zinc-300 px-3"/></label></>:null}{error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}{notice?<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>:null}<button disabled={loading} className="min-h-11 w-full rounded-lg bg-emerald-800 px-4 text-sm font-semibold text-white disabled:opacity-60">{loading?"Ansluter…":signedIn?"Gå med i skolan":mode==="signup"?"Skapa konto och gå med":"Logga in och gå med"}</button></form>
  </div>;
}
