"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { parseStaffList,type StaffCandidate } from "@/lib/operator/validation";

type PreviewRow={row_number:number;full_name:string;email:string;status:string};
type ResultRow={fullName:string;email:string;token:string};
const statusText:Record<string,string>={ready:"Redo",existing_account:"Befintligt konto – kan bjudas in",invalid_name:"Ogiltigt namn",invalid_email:"Ogiltig e-post",duplicate_in_batch:"Dubblett i listan",existing_user:"Har redan en skolprofil",active_invitation:"Har redan en aktiv inbjudan"};

export function BulkStaffOnboarding({schoolId}:{schoolId:string}){
  const router=useRouter();const [input,setInput]=useState("");const [candidates,setCandidates]=useState<StaffCandidate[]>([]);const [preview,setPreview]=useState<PreviewRow[]>([]);const [results,setResults]=useState<ResultRow[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [copied,setCopied]=useState<string|null>(null);
  async function previewBatch(){setError("");setResults([]);const parsed=parseStaffList(input);if(!parsed.length){setError("Klistra in minst en person.");return;}const localErrors=parsed.filter((row)=>row.error);if(localErrors.length){setPreview(parsed.map((row)=>({row_number:row.rowNumber,full_name:row.fullName,email:row.email,status:row.error??"Redo"})));setCandidates([]);return;}const people=parsed.map(({fullName,email})=>({fullName,email}));setBusy(true);const response=await fetch(`/api/operator/schools/${schoolId}/staff-invitations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"preview",people})});const data=await response.json() as {rows?:PreviewRow[];error?:string};setBusy(false);if(!response.ok||!data.rows){setError(data.error??"Listan kunde inte kontrolleras.");return;}setCandidates(people);setPreview(data.rows);}
  async function createBatch(){setBusy(true);setError("");const response=await fetch(`/api/operator/schools/${schoolId}/staff-invitations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"create",people:candidates})});const data=await response.json() as {invitations?:ResultRow[];error?:string};setBusy(false);if(!response.ok||!data.invitations){setError(data.error??"Inbjudningarna kunde inte skapas. Inga rader skapades.");return;}setResults(data.invitations);setPreview([]);setCandidates([]);setInput("");router.refresh();}
  async function copy(result:ResultRow){const url=`${window.location.origin}/invite/${result.token}`;await navigator.clipboard.writeText(url);setCopied(result.email)}
  const valid=preview.length>0&&preview.every((row)=>["ready","existing_account"].includes(row.status));
  return <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">Onboarda personal</h2><p className="mt-1 text-sm leading-6 text-zinc-600">Klistra in en person per rad: <strong>Namn, e-postadress</strong>. Högst 100 personer åt gången.</p><textarea value={input} onChange={(event)=>{setInput(event.target.value);setPreview([]);setCandidates([]);setResults([])}} rows={6} placeholder={"Anna Andersson, anna@skola.se\nErik Eriksson, erik@skola.se"} className="mt-4 w-full rounded-lg border border-zinc-300 p-3 text-sm"/><button type="button" disabled={busy} onClick={()=>void previewBatch()} className="mt-3 min-h-11 rounded-lg bg-emerald-800 px-5 text-sm font-semibold text-white disabled:opacity-60">{busy?"Kontrollerar…":"Förhandsgranska"}</button>{error?<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}{preview.length?<div className="mt-5"><h3 className="font-semibold">Förhandsgranskning</h3><ul className="mt-2 divide-y divide-zinc-100 rounded-lg border border-zinc-200">{preview.map((row)=><li key={`${row.row_number}-${row.email}`} className="p-3 text-sm"><p className="font-medium">{row.full_name||`Rad ${row.row_number}`}</p><p className="text-zinc-500">{row.email||"Ingen giltig e-post"}</p><p className={`mt-1 text-xs font-semibold ${["ready","existing_account"].includes(row.status)?"text-emerald-700":"text-red-700"}`}>{statusText[row.status]??row.status}</p></li>)}</ul>{valid?<button type="button" disabled={busy} onClick={()=>void createBatch()} className="mt-4 min-h-11 rounded-lg bg-emerald-800 px-5 text-sm font-semibold text-white disabled:opacity-60">{busy?"Skapar…":`Skapa ${preview.length} inbjudningar`}</button>:<p className="mt-3 text-sm text-red-700">Rätta konflikterna innan inbjudningarna skapas. Ingen del av listan har sparats.</p>}</div>:null}{results.length?<div className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-4"><h3 className="font-semibold text-emerald-950">Inbjudningarna är skapade</h3><p className="mt-1 text-xs text-emerald-800">Länkarna visas bara nu. Kopiera dem innan du lämnar sidan.</p><ul className="mt-3 space-y-3">{results.map((result)=><li key={result.email} className="rounded-lg bg-white p-3"><p className="font-medium">{result.fullName}</p><p className="text-sm text-zinc-500">{result.email}</p><button onClick={()=>void copy(result)} className="mt-2 min-h-10 rounded-lg border border-emerald-700 px-3 text-sm font-semibold text-emerald-900">{copied===result.email?"Kopierad":"Kopiera inbjudningslänk"}</button></li>)}</ul></div>:null}</section>;
}
