import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { BulkStaffOnboarding } from "@/components/operator/bulk-staff-onboarding";
import { InvitationActions } from "@/components/operator/invitation-actions";
import { OperatorShell } from "@/components/operator/operator-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { requireOperator } from "@/lib/auth/operator";
import { createClient } from "@/lib/supabase/server";

export const metadata:Metadata={title:"Skola · Operatör"};
type School={id:string;name:string;slug:string};type User={id:string;full_name:string;email:string;role:string;created_at:string};type Invite={id:string;full_name:string;email:string;status:string;created_at:string;expires_at:string};
const roleLabels:Record<string,string>={school_admin:"Skoladministratör",staff:"Personal",member:"Medlem"};
const invitationStatusLabels:Record<string,string>={pending:"Väntar",accepted:"Aktiverad",expired:"Utgången",cancelled:"Avbruten"};
export default async function OperatorSchoolPage({params}:{params:Promise<{id:string}>}){await requireOperator();const {id}=await params;if(!/^[0-9a-f-]{36}$/i.test(id))notFound();const supabase=await createClient();const [{data:schoolData},{data:users,error:usersError},{data:invites,error:invitesError}]=await Promise.all([supabase.rpc("operator_get_school",{target_school_id:id}),supabase.rpc("operator_list_school_users",{target_school_id:id}),supabase.rpc("operator_list_school_invitations",{target_school_id:id})]);const school=((schoolData??[])[0]??null) as School|null;if(!school)notFound();const userRows=(users??[]) as User[];const inviteRows=(invites??[]) as Invite[];return <OperatorShell><PageHeader eyebrow={school.slug} title={school.name} description="Skicka oss personalens mejladresser så sköter vi resten."/><BulkStaffOnboarding schoolId={id}/><div className="mt-7 grid gap-6 lg:grid-cols-2"><section><h2 className="mb-3 font-semibold">Aktiva användare</h2>{usersError?<p className="rounded-xl bg-red-50 p-4 text-sm text-red-800">Användarna kunde inte hämtas.</p>:userRows.length===0?<EmptyState title="Inga aktiva användare" description="Personal visas här efter att de har accepterat sin inbjudan."/>:<ul className="divide-y divide-zinc-100 overflow-hidden rounded-xl border border-zinc-200 bg-white">{userRows.map((user)=><li key={user.id} className="p-4"><p className="font-medium">{user.full_name}</p><p className="text-sm text-zinc-500">{user.email} · {roleLabels[user.role]??user.role}</p></li>)}</ul>}</section><section><h2 className="mb-3 font-semibold">Personalinbjudningar</h2>{invitesError?<p className="rounded-xl bg-red-50 p-4 text-sm text-red-800">Inbjudningarna kunde inte hämtas.</p>:inviteRows.length===0?<EmptyState title="Inga personalinbjudningar" description="Klistra in personal ovan för att skapa individuella länkar."/>:<ul className="divide-y divide-zinc-100 overflow-hidden rounded-xl border border-zinc-200 bg-white">{inviteRows.map((invite)=><li key={invite.id} className="p-4"><p className="font-medium">{invite.full_name}</p><p className="text-sm text-zinc-500">{invite.email}</p><p className="mt-1 text-xs font-semibold uppercase text-zinc-500">{invitationStatusLabels[invite.status]??invite.status}</p><InvitationActions id={invite.id} status={invite.status}/></li>)}</ul>}</section></div></OperatorShell>}
